# Generated by Django 5.2.4 on 2025-08-15 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="time",
        ),
        migrations.AddField(
            model_name="review",
            name="feedback",
            field=models.CharField(default="", max_length=512),
        ),
        migrations.AddField(
            model_name="review",
            name="sentiment",
            field=models.CharField(default="", max_length=20),
        ),
    ]
