# Generated by Django 5.2.4 on 2025-08-15 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0002_remove_review_time_review_feedback_review_sentiment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="user",
        ),
    ]
