# Generated by Django 5.2.4 on 2025-08-17 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_remove_review_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='feedback',
            new_name='feedback1',
        ),
        migrations.AddField(
            model_name='review',
            name='feedback2',
            field=models.CharField(blank=True, default='', max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='feedback3',
            field=models.CharField(blank=True, default='', max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='username',
            field=models.CharField(default='Anonymous', max_length=255),
        ),
    ]
