# Generated by Django 5.2.4 on 2025-08-17 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_rename_feedback_review_feedback1_review_feedback2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='company',
            field=models.CharField(default='X', max_length=100),
        ),
    ]
